### ISSUE TITLE
The version is almost out dated

### ISSUE THREAD

**Issue by alaaelgndy** [kadena-io/docker-compose-chainweb-node#1]
This version of chainweb node will stop to work at 2022-02-24 00:00:00 UTC. Please upgrade to a new version before that date.

Is there any way to upgrade the version? from the .env file or even in the docker compose yaml ??

Thanks in advence

**Comment by qubitqualia** [comment]
It looks like docker-compose.yaml is already targeting the latest image for chainweb-node:

`image:  ghcr.io/kadena-io/chainweb-node/ubuntu:latest`

**Comment by larskuhtz** [comment]
You would have to pull the latest image before that date and restart the node:

```sh
docker compose pull
docker compose up -d
```

Usually a new version is released about 7-5 days before the previous version expires.
